//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongGiangDay
    {
        public int MaGV { get; set; }
        public int MaLop { get; set; }
        public int MaMon { get; set; }
        public int TietBatDau { get; set; }
        public int TietKetThuc { get; set; }
        public int Thu { get; set; }
        public int NamHoc { get; set; }
        public int MaHocKy { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
