//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XepLoaiHocSinh
    {
        public int MaHS { get; set; }
        public string TenXepLoai { get; set; }
        public int NamHoc { get; set; }
        public int MaHocKy { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual XepLoai XepLoai { get; set; }
    }
}
